### ISSUE TITLE
Unable to build using Visual Studio 2019

### ISSUE THREAD

**Issue by Prathapdom** [GoSecure/xfsc#1]
I have imported the source to my Visual Studio 2019 and installed the "Desktop development with C++" but during build it says "E1574	static assertion failed with "Windows headers require the default packing option. Changing this can lead to memory corruption. This diagnostic can be disabled by building with WINDOWS_IGNORE_PACKING_MISMATCH defined"

Is there any specific package or the version of Visual Studio to be installed inorder to build?

![anydesk00001](https://user-images.githubusercontent.com/25145067/175519534-6a4f8e1c-5a78-41e6-a9bd-d9136e41ca26.png)

The header link is not redirecting to the correct page now.

**Comment by obilodeau** [comment]
Did you try?

Project Settings > C/C++ > Code Generation > Struct Member Alignment (change to Default)

**Comment by obilodeau** [comment]
Other things to try:

Defining `WINDOWS_IGNORE_PACKING_MISMATCH` in Property Pages -> C/C++ -> Preprocessor -> Add to Preprocessor Definitions. Use a semicolon to separate definitions.

Yet another suggestion can be found here: https://stackoverflow.com/questions/56570681/static-assertion-failed-with-windows-headers-require-the-default-packing-option

Please let me know what worked for you.

**Comment by Prathapdom** [comment]
Yes, Struct Member Alignment as already at Default the project build successfully after adding Preprocessor definitions. Thanks @obilodeau
